global:
  scrape_interval: 5s # Fast scraping for local testing

scrape_configs:
  - job_name: 'payflow_gateway'
    # For Mac + Docker, host.docker.internal routes to your local machine
    static_configs:
      - targets: ['host.docker.internal:8000']