global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'payflow_gateway'
    static_configs:
      - targets: ['gateway:8000']
  - job_name: 'bank_hdfc'
    static_configs:
      - targets: ['bank-hdfc:8001']
  - job_name: 'bank_sbi'
    static_configs:
      - targets: ['bank-sbi:8002']
  - job_name: 'ledger'
    static_configs:
      - targets: ['ledger:8003']
  - job_name: 'notifications'
    static_configs:
      - targets: ['notifications:8004']
  - job_name: 'reconciliation'
    static_configs:
      - targets: ['reconciliation-worker:8006']